### ISSUE TITLE
LED not always displayed correctly

### ISSUE THREAD

**Issue by fwunsch** [kit-cel/gr-dab#23]
LEDs only display when the GUI ist started from the python/GUI folder.

**Comment by MoritzLucaSchmid** [comment]
Is the DABstep logo not displayed correctly as well?

**Comment by marcusmueller** [comment]
> Is the DABstep logo not displayed correctly as well?

Indeed, it's missing when the led icons are displayed incorrectly.

**Comment by marcusmueller** [comment]
hopefully fixed by 94db7bf

**Comment by marcusmueller** [comment]
Merged into master
