### ISSUE TITLE
Receiver needs a stop button

### ISSUE THREAD

**Issue by fwunsch** [kit-cel/gr-dab#24]
"Start receiver" should probably switch to "stop receiver" once started.

**Comment by marcusmueller** [comment]
I'm now confused what the difference between the "stop receiver" button (which replaces the "start receiver" button) and the "Stop" button at the bottom of the receive tab is.

**Comment by MoritzLucaSchmid** [comment]
When the receiver is running and audio is selected, the audio stop button and the stop receiver button have the same functionality. I am going to make the audio player independed from the flowgraph start/stop by using a valve block, stopping only the pcm streams to audio sink / wav file sink.

**Comment by MoritzLucaSchmid** [comment]
solved by #6228a4ba6a06fb66549e4560b783fae080232d17
