### ISSUE TITLE
TypeError: make() takes exactly 10 arguments (8 given)

### ISSUE THREAD

**Issue by steven-bloom** [kit-cel/gr-dab#33]
Hi, everyone. 
I'm trying to implement dab_transmiter.grc, but facing the following problem. Tell me please how to solve the issue 
![screenshot from 2017-10-09 16-38-14](https://user-images.githubusercontent.com/30798903/31343775-e316a96a-ad10-11e7-8739-94bca0db0cb6.png)

**Comment by MLsmd** [comment]
Hey Steven,
sorry for the delay..
I rewrote the FIB source and forgot to update the grc files.
I am going to publish a new version of gr-dab in some hours, with a whole new synchronization and new structure of the blocks (the trigger stream is now replaced by simple tags). The grc files will be updated then.
Best
Luca

**Comment by steven-bloom** [comment]
Thank you very mutch, Luca! :)

**Comment by MLsmd** [comment]
The branch "working_branch" should work now with the improved sync and updated grc blocks. You can check it out now.
I am going to remove all the "old" files after a review of my mentors and merge it into master.
If errors occur, I am happy if you tell me :)

Best
Luca

**Comment by steven-bloom** [comment]
Hello, Luca! 
After i successfully have rebuild Projekt from working_branch i recived the following message:
Executing: /usr/bin/python -u /home/gnuradio/gr-dab/examples/top_block.py

> gr::log :DEBUG: reed_solomon_encode_bb0 - RS init succeeded
> Using Volk machine: avx_64_mmx_orc
> gr::log :INFO: mp4_encode_sb0 - AOT set to AAC LC (Low Complexity)
> gr::log :INFO: mp4_encode_sb0 - Using 14 subchannels. channels = 2, sample_rate = 32000
> gr::log :INFO: mp4_encode_sb0 - AAC bitrate set to: 112000
> gr::log :INFO: mp4_encode_sb0 - AAC enc init succeeded
> gr::log :INFO: mp4_encode_sb0 - AAC Encoding: framelen = 960
> gr::log :DEBUG: dab_transmission_frame_mux_bb0 - MUX init with: fic_len = 1152, subch_total_size = 84, vlen_out = 28800
> gr::log :DEBUG: dab_transmission_frame_mux_bb0 - key num_subch: 1
> Traceback (most recent call last):
>   File "/home/gnuradio/gr-dab/examples/top_block.py", line 135, in <module>
>     main()
>   File "/home/gnuradio/gr-dab/examples/top_block.py", line 123, in main
>     tb = top_block_cls()
>   File "/home/gnuradio/gr-dab/examples/top_block.py", line 93, in __init__
>     self.connect((self.blocks_wavfile_source_0, 1), (self.blocks_float_to_short_0_0, 0))    
>   File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 47, in wrapped
>     func(self, src, src_port, dst, dst_port)
>   File "/usr/lib/python2.7/dist-packages/gnuradio/gr/hier_block2.py", line 110, in connect
>     self.primitive_connect(*args)
>   File "/usr/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 5331, in primitive_connect
>     return _runtime_swig.top_block_sptr_primitive_connect(self, *args)
> ValueError: port number 1 exceeds max of 0
> 
> >>> Done  

I'm not entirely sure if the error caused by the application or by swig-module
![screenshot from 2017-11-01 12-36-01](https://user-images.githubusercontent.com/30798903/32273453-d80107e2-bf02-11e7-878b-816f16a445b3.png)
.

Beste Grüße, :)
Steven

**Comment by MLsmd** [comment]
Hi Steven,
the cmake Terminal shortcut you sent me per mail, says, that errors occured, because libtoolame-dab was not found. Can you install libtoolame-dab as descibed in the README by initalizing the submodule for the library with:
$ git submodule update --init
$ mkdir build
$ cd build
$ cmake ../
$ make
$ sudo make install
$ sudo ldconfig
and see if the error still occurs.
This might solve your actual issue as well.

Best :)
Luca

**Comment by steven-bloom** [comment]
Hey, Luca,
I am sorry, at first time i have attached the wrong Screen-shoot. Now it's fixed.  The Problem is, that i receive the error-message:
File "/usr/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 5331, in primitive_connect
return _runtime_swig.top_block_sptr_primitive_connect(self, *args)
ValueError: port number 1 exceeds max of 0
Sincerely yours,
Steven

**Comment by MLsmd** [comment]
After reading the error message: I think your audio file contains only a mono channel, so the wav source cannot provide 2 output ports. You can check that by creating another flowgraph with just your wav source and an audio sink. If this is the case, you can just connect the one chain of the wav source with both input ports of the MPEG encoder.
I hope this solves your issue.

Best
Luca

**Comment by steven-bloom** [comment]
Thanks, Luca.
I tried with another Audio, and everything works like a charm :)
Thank you one more time for this wonderfull OOT-Projekt! 

Best,
Steven
